### ISSUE TITLE
Clearly separate CSS media embossed vs. print

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/pipeline-mod-braille#5]
E.g. always wrap print CSS in `@media print { }` , even inside style attributes.

``` css
@media print { font-style: italic }
```

css:inline could have an option "media" (&lt;media-query&gt;) to filter the stylesheets and only inline rules that match the media query.
